from . import admin_panel
from . import start
from . import menu1
from . import k_menu1
from . import namoz_vaqtlari
from . import k_namoz_vaqtlari
from . import sura_tarjima
from . import k_sura_tarjima
from . import help
from . import echo
